CSS      = reveal.js/css/...
JS       = reveal.js/js/...
LIB      = reveal.js/lib/...
PLUGIN   = reveal.js/plugin/...
TEMPLATE = tmpl/...

bindata: assets.go
	go-bindata -o=assets.go $(CSS) $(JS) $(LIB) $(PLUGIN) $(TEMPLATE)

debug-bindata: assets.go
	go-bindata --debug=true -o=assets.go $(CSS) $(JS) $(LIB) $(PLUGIN) $(TEMPLATE)
